version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: loginform
      POSTGRES_PASSWORD: loginform123!
      POSTGRES_DB: loginform_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
